import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import localFont from "next/font/local";
import MobileSideView from "./components/MobileSideView";
import { auth } from "@/auth";
import "./globals.css";
const myFont = localFont({
  src: "./assets/Ubuntu-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Movie Box",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session)
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Header session={session} />
        {children}
        <MobileSideView session={session} />
        <Footer />
      </body>
    </html>
  );
}
